; Generated from tools/zh/layouts.py. No runtime layout selection.
DEF ZH_DIALOGUE_LEFT EQU 1
DEF ZH_DIALOGUE_TOP EQU 13
DEF ZH_DIALOGUE_WIDTH EQU 18
DEF ZH_DIALOGUE_STEP EQU 2
DEF ZH_MOVE_LIST_LEFT EQU 1
DEF ZH_MOVE_LIST_TOP EQU 9
DEF ZH_MOVE_LIST_WIDTH EQU 18
DEF ZH_MOVE_LIST_STEP EQU 2
DEF ZH_START_MENU_LEFT EQU 12
DEF ZH_START_MENU_TOP EQU 1
DEF ZH_START_MENU_WIDTH EQU 7
DEF ZH_START_MENU_STEP EQU 2
