; Default dialogue geometry. Profile builder replaces this in isolated staging.
DEF ZH_LAYOUT_LEFT_TILES EQU 1
DEF ZH_LAYOUT_WIDTH_TILES EQU 18
DEF ZH_LAYOUT_WIDTH_PX EQU 144
DEF ZH_LAYOUT_TOP_TILE EQU 13
DEF ZH_LAYOUT_LINE_STEP_TILES EQU 2
DEF ZH_LAYOUT_GLYPH_Y_OFFSET EQU 2
ASSERT ZH_LAYOUT_LEFT_TILES >= 1
ASSERT ZH_LAYOUT_LEFT_TILES + ZH_LAYOUT_WIDTH_TILES <= 19
ASSERT ZH_LAYOUT_WIDTH_PX == ZH_LAYOUT_WIDTH_TILES * 8
ASSERT ZH_LAYOUT_TOP_TILE == 13 && ZH_LAYOUT_LINE_STEP_TILES == 2
ASSERT ZH_LAYOUT_GLYPH_Y_OFFSET >= 0 && ZH_LAYOUT_GLYPH_Y_OFFSET <= 4

; Align 8px Latin glyphs to the bottom of the 12px CJK cell.
DEF ZH_LAYOUT_ASCII_Y_OFFSET EQU 4
ASSERT ZH_LAYOUT_ASCII_Y_OFFSET == 4
