; Fixed DFS block geometry. Numeric and common-font tiles are never allocated.
DEF ZH_VRAM_BOTH EQU 3
DEF ZH_VRAM_BANK0_ONLY EQU 1
DEF ZH_VRAM_BANK1_ONLY EQU 2
DEF ZH_VRAM_POLICY_DEPTH EQU 8
DEF ZH_CACHE_FIRST_TILE EQU $80
; PrintLevel writes <LV> directly at $d6. Keep that and the suffix static.
DEF ZH_CACHE_END_TILE EQU $d6
DEF ZH_CACHE_BLOCKS_PER_BANK EQU (ZH_CACHE_END_TILE - ZH_CACHE_FIRST_TILE) / 2
DEF ZH_CACHE_BLOCKS EQU ZH_CACHE_BLOCKS_PER_BANK * 2
DEF ZH_CACHE_KEY_SIZE EQU 4
ASSERT ZH_CACHE_END_TILE <= CHARVAL("0")
ASSERT ZH_CACHE_END_TILE <= CHARVAL("<LV>")
ASSERT ZH_CACHE_FIRST_TILE % 2 == 0
ASSERT ZH_CACHE_END_TILE % 2 == 0
ASSERT ZH_CACHE_BLOCKS < $100
