ZhSummaryMoves::
 xor a
 ld [wZhSummaryMovesActive],a
 ld a,[wTempMonMoves+0]
 and a
 jr z,.admit0
 call .lookup
 jp c,.fallback
.admit0
 ld a,[wTempMonMoves+1]
 and a
 jr z,.admit1
 call .lookup
 jp c,.fallback
.admit1
 ld a,[wTempMonMoves+2]
 and a
 jr z,.admit2
 call .lookup
 jp c,.fallback
.admit2
 ld a,[wTempMonMoves+3]
 and a
 jr z,.admit3
 call .lookup
 jp c,.fallback
.admit3
 ld a,1
 ld [wZhSummaryMovesActive],a
 hlbgcoord 4,1,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+0],a
 hlbgcoord 5,1,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+1],a
 hlbgcoord 6,1,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+2],a
 hlbgcoord 7,1,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+3],a
 hlbgcoord 8,1,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+4],a
 hlbgcoord 9,1,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+5],a
 hlbgcoord 10,1,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+6],a
 hlbgcoord 11,1,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+7],a
 ld a,[wTempMonMoves+0]
 ld [wZhMoveIds+0],a
 hlbgcoord 4,3,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+8],a
 hlbgcoord 5,3,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+9],a
 hlbgcoord 6,3,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+10],a
 hlbgcoord 7,3,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+11],a
 hlbgcoord 8,3,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+12],a
 hlbgcoord 9,3,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+13],a
 hlbgcoord 10,3,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+14],a
 hlbgcoord 11,3,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+15],a
 ld a,[wTempMonMoves+1]
 ld [wZhMoveIds+1],a
 hlbgcoord 4,5,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+16],a
 hlbgcoord 5,5,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+17],a
 hlbgcoord 6,5,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+18],a
 hlbgcoord 7,5,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+19],a
 hlbgcoord 8,5,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+20],a
 hlbgcoord 9,5,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+21],a
 hlbgcoord 10,5,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+22],a
 hlbgcoord 11,5,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+23],a
 ld a,[wTempMonMoves+2]
 ld [wZhMoveIds+2],a
 hlbgcoord 4,7,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+24],a
 hlbgcoord 5,7,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+25],a
 hlbgcoord 6,7,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+26],a
 hlbgcoord 7,7,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+27],a
 hlbgcoord 8,7,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+28],a
 hlbgcoord 9,7,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+29],a
 hlbgcoord 10,7,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+30],a
 hlbgcoord 11,7,wSummaryScreenWindowBuffer
 ld a,[hl]
 ld [wZhMovePPText+31],a
 ld a,[wTempMonMoves+3]
 ld [wZhMoveIds+3],a
 ldh a,[rWBK]
 push af
 ld a,BANK(wZhMovePixels)
 ldh [rWBK],a
 ld hl,wZhMovePixels
 ld bc,1920
 xor a
 rst ByteFill
 ld a,[wZhMoveIds+0]
 and a
 jp z,.rowDone0
 call .lookup
 ld de,wZhMovePixels+0
 call .copyPixelRow
 ld de,wZhMovePixels+2
 call .copyPixelRow
 ld de,wZhMovePixels+4
 call .copyPixelRow
 ld de,wZhMovePixels+6
 call .copyPixelRow
 ld de,wZhMovePixels+8
 call .copyPixelRow
 ld de,wZhMovePixels+10
 call .copyPixelRow
 ld de,wZhMovePixels+12
 call .copyPixelRow
 ld de,wZhMovePixels+14
 call .copyPixelRow
 ld de,wZhMovePixels+16
 call .copyPixelRow
 ld de,wZhMovePixels+18
 call .copyPixelRow
 ld de,wZhMovePixels+20
 call .copyPixelRow
 ld de,wZhMovePixels+22
 call .copyPixelRow
 ld de,wZhMovePixels+24
 call .copyPixelRow
 ld de,wZhMovePixels+26
 call .copyPixelRow
 ld de,wZhMovePixels+28
 call .copyPixelRow
 ld de,wZhMovePixels+30
 call .copyPixelRow
 ld de,wZhMovePixels+32
 call .copyPixelRow
 ld de,wZhMovePixels+34
 call .copyPixelRow
 ld de,wZhMovePixels+36
 call .copyPixelRow
 ld de,wZhMovePixels+38
 call .copyPixelRow
 ld de,wZhMovePixels+40
 call .copyPixelRow
 ld de,wZhMovePixels+42
 call .copyPixelRow
 ld de,wZhMovePixels+44
 call .copyPixelRow
 ld de,wZhMovePixels+46
 call .copyPixelRow
 ld de,wZhMovePixels+48
 call .copyPixelRow
 ld de,wZhMovePixels+50
 call .copyPixelRow
 ld de,wZhMovePixels+52
 call .copyPixelRow
 ld de,wZhMovePixels+54
 call .copyPixelRow
 ld de,wZhMovePixels+56
 call .copyPixelRow
 ld de,wZhMovePixels+58
 call .copyPixelRow
 ld de,wZhMovePixels+60
 call .copyPixelRow
 ld de,wZhMovePixels+62
 call .copyPixelRow
 ld de,wZhMovePixels+64
 call .copyPixelRow
 ld de,wZhMovePixels+66
 call .copyPixelRow
 ld de,wZhMovePixels+68
 call .copyPixelRow
 ld de,wZhMovePixels+70
 call .copyPixelRow
 ld de,wZhMovePixels+72
 call .copyPixelRow
 ld de,wZhMovePixels+74
 call .copyPixelRow
 ld de,wZhMovePixels+76
 call .copyPixelRow
 ld de,wZhMovePixels+78
 call .copyPixelRow
 ld de,wZhMovePixels+80
 call .copyPixelRow
 ld de,wZhMovePixels+82
 call .copyPixelRow
 ld de,wZhMovePixels+84
 call .copyPixelRow
 ld de,wZhMovePixels+86
 call .copyPixelRow
 ld de,wZhMovePixels+88
 call .copyPixelRow
 ld de,wZhMovePixels+90
 call .copyPixelRow
 ld de,wZhMovePixels+92
 call .copyPixelRow
 ld de,wZhMovePixels+94
 call .copyPixelRow
 ld de,wZhMovePixels+96
 call .copyPixelRow
 ld de,wZhMovePixels+98
 call .copyPixelRow
 ld de,wZhMovePixels+100
 call .copyPixelRow
 ld de,wZhMovePixels+102
 call .copyPixelRow
 ld de,wZhMovePixels+104
 call .copyPixelRow
 ld de,wZhMovePixels+106
 call .copyPixelRow
 ld de,wZhMovePixels+108
 call .copyPixelRow
 ld de,wZhMovePixels+110
 call .copyPixelRow
 ld de,wZhMovePixels+112
 call .copyPixelRow
 ld de,wZhMovePixels+114
 call .copyPixelRow
 ld de,wZhMovePixels+116
 call .copyPixelRow
 ld de,wZhMovePixels+118
 call .copyPixelRow
 ld de,wZhMovePixels+120
 call .copyPixelRow
 ld de,wZhMovePixels+122
 call .copyPixelRow
 ld de,wZhMovePixels+124
 call .copyPixelRow
 ld de,wZhMovePixels+126
 call .copyPixelRow
 ld de,wZhMovePixels+192
 call .copyPixelRow
 ld de,wZhMovePixels+194
 call .copyPixelRow
 ld de,wZhMovePixels+196
 call .copyPixelRow
 ld de,wZhMovePixels+198
 call .copyPixelRow
 ld de,wZhMovePixels+200
 call .copyPixelRow
 ld de,wZhMovePixels+202
 call .copyPixelRow
 ld de,wZhMovePixels+204
 call .copyPixelRow
 ld de,wZhMovePixels+206
 call .copyPixelRow
 ld de,wZhMovePixels+208
 call .copyPixelRow
 ld de,wZhMovePixels+210
 call .copyPixelRow
 ld de,wZhMovePixels+212
 call .copyPixelRow
 ld de,wZhMovePixels+214
 call .copyPixelRow
 ld de,wZhMovePixels+216
 call .copyPixelRow
 ld de,wZhMovePixels+218
 call .copyPixelRow
 ld de,wZhMovePixels+220
 call .copyPixelRow
 ld de,wZhMovePixels+222
 call .copyPixelRow
 ld de,wZhMovePixels+224
 call .copyPixelRow
 ld de,wZhMovePixels+226
 call .copyPixelRow
 ld de,wZhMovePixels+228
 call .copyPixelRow
 ld de,wZhMovePixels+230
 call .copyPixelRow
 ld de,wZhMovePixels+232
 call .copyPixelRow
 ld de,wZhMovePixels+234
 call .copyPixelRow
 ld de,wZhMovePixels+236
 call .copyPixelRow
 ld de,wZhMovePixels+238
 call .copyPixelRow
 ld de,wZhMovePixels+240
 call .copyPixelRow
 ld de,wZhMovePixels+242
 call .copyPixelRow
 ld de,wZhMovePixels+244
 call .copyPixelRow
 ld de,wZhMovePixels+246
 call .copyPixelRow
 ld de,wZhMovePixels+248
 call .copyPixelRow
 ld de,wZhMovePixels+250
 call .copyPixelRow
 ld de,wZhMovePixels+252
 call .copyPixelRow
 ld de,wZhMovePixels+254
 call .copyPixelRow
 ld de,wZhMovePixels+256
 call .copyPixelRow
 ld de,wZhMovePixels+258
 call .copyPixelRow
 ld de,wZhMovePixels+260
 call .copyPixelRow
 ld de,wZhMovePixels+262
 call .copyPixelRow
 ld de,wZhMovePixels+264
 call .copyPixelRow
 ld de,wZhMovePixels+266
 call .copyPixelRow
 ld de,wZhMovePixels+268
 call .copyPixelRow
 ld de,wZhMovePixels+270
 call .copyPixelRow
 ld de,wZhMovePixels+272
 call .copyPixelRow
 ld de,wZhMovePixels+274
 call .copyPixelRow
 ld de,wZhMovePixels+276
 call .copyPixelRow
 ld de,wZhMovePixels+278
 call .copyPixelRow
 ld de,wZhMovePixels+280
 call .copyPixelRow
 ld de,wZhMovePixels+282
 call .copyPixelRow
 ld de,wZhMovePixels+284
 call .copyPixelRow
 ld de,wZhMovePixels+286
 call .copyPixelRow
 ld de,wZhMovePixels+288
 call .copyPixelRow
 ld de,wZhMovePixels+290
 call .copyPixelRow
 ld de,wZhMovePixels+292
 call .copyPixelRow
 ld de,wZhMovePixels+294
 call .copyPixelRow
 ld de,wZhMovePixels+296
 call .copyPixelRow
 ld de,wZhMovePixels+298
 call .copyPixelRow
 ld de,wZhMovePixels+300
 call .copyPixelRow
 ld de,wZhMovePixels+302
 call .copyPixelRow
 ld de,wZhMovePixels+304
 call .copyPixelRow
 ld de,wZhMovePixels+306
 call .copyPixelRow
 ld de,wZhMovePixels+308
 call .copyPixelRow
 ld de,wZhMovePixels+310
 call .copyPixelRow
 ld de,wZhMovePixels+312
 call .copyPixelRow
 ld de,wZhMovePixels+314
 call .copyPixelRow
 ld de,wZhMovePixels+316
 call .copyPixelRow
 ld de,wZhMovePixels+318
 call .copyPixelRow
 ld hl,.PP+0
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+258],a
 ld [wZhMovePixels+259],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+260],a
 ld [wZhMovePixels+261],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+262],a
 ld [wZhMovePixels+263],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+264],a
 ld [wZhMovePixels+265],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+266],a
 ld [wZhMovePixels+267],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+268],a
 ld [wZhMovePixels+269],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+270],a
 ld [wZhMovePixels+271],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+448],a
 ld [wZhMovePixels+449],a
.ppSkip0_0
 ld hl,.PP+8
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+274],a
 ld [wZhMovePixels+275],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+276],a
 ld [wZhMovePixels+277],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+278],a
 ld [wZhMovePixels+279],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+280],a
 ld [wZhMovePixels+281],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+282],a
 ld [wZhMovePixels+283],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+284],a
 ld [wZhMovePixels+285],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+286],a
 ld [wZhMovePixels+287],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+464],a
 ld [wZhMovePixels+465],a
.ppSkip0_1
 ld hl,.PP+16
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+290],a
 ld [wZhMovePixels+291],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+292],a
 ld [wZhMovePixels+293],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+294],a
 ld [wZhMovePixels+295],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+296],a
 ld [wZhMovePixels+297],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+298],a
 ld [wZhMovePixels+299],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+300],a
 ld [wZhMovePixels+301],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+302],a
 ld [wZhMovePixels+303],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+480],a
 ld [wZhMovePixels+481],a
.ppSkip0_2
 ld a,[wZhMovePPText+3]
 cp $7f
 jr z,.ppSkip0_3
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+306],a
 ld [wZhMovePixels+307],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+308],a
 ld [wZhMovePixels+309],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+310],a
 ld [wZhMovePixels+311],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+312],a
 ld [wZhMovePixels+313],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+314],a
 ld [wZhMovePixels+315],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+316],a
 ld [wZhMovePixels+317],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+318],a
 ld [wZhMovePixels+319],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+496],a
 ld [wZhMovePixels+497],a
.ppSkip0_3
 ld a,[wZhMovePPText+4]
 cp $7f
 jr z,.ppSkip0_4
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+322],a
 ld [wZhMovePixels+323],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+324],a
 ld [wZhMovePixels+325],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+326],a
 ld [wZhMovePixels+327],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+328],a
 ld [wZhMovePixels+329],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+330],a
 ld [wZhMovePixels+331],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+332],a
 ld [wZhMovePixels+333],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+334],a
 ld [wZhMovePixels+335],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+512],a
 ld [wZhMovePixels+513],a
.ppSkip0_4
 ld a,[wZhMovePPText+5]
 cp $7f
 jr z,.ppSkip0_5
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+338],a
 ld [wZhMovePixels+339],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+340],a
 ld [wZhMovePixels+341],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+342],a
 ld [wZhMovePixels+343],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+344],a
 ld [wZhMovePixels+345],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+346],a
 ld [wZhMovePixels+347],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+348],a
 ld [wZhMovePixels+349],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+350],a
 ld [wZhMovePixels+351],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+528],a
 ld [wZhMovePixels+529],a
.ppSkip0_5
 ld a,[wZhMovePPText+6]
 cp $7f
 jr z,.ppSkip0_6
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+354],a
 ld [wZhMovePixels+355],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+356],a
 ld [wZhMovePixels+357],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+358],a
 ld [wZhMovePixels+359],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+360],a
 ld [wZhMovePixels+361],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+362],a
 ld [wZhMovePixels+363],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+364],a
 ld [wZhMovePixels+365],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+366],a
 ld [wZhMovePixels+367],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+544],a
 ld [wZhMovePixels+545],a
.ppSkip0_6
 ld a,[wZhMovePPText+7]
 cp $7f
 jr z,.ppSkip0_7
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+370],a
 ld [wZhMovePixels+371],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+372],a
 ld [wZhMovePixels+373],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+374],a
 ld [wZhMovePixels+375],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+376],a
 ld [wZhMovePixels+377],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+378],a
 ld [wZhMovePixels+379],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+380],a
 ld [wZhMovePixels+381],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+382],a
 ld [wZhMovePixels+383],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+560],a
 ld [wZhMovePixels+561],a
.ppSkip0_7
.rowDone0
 ld a,[wZhMoveIds+1]
 and a
 jp z,.rowDone1
 call .lookup
 ld de,wZhMovePixels+390
 call .copyPixelRow
 ld de,wZhMovePixels+392
 call .copyPixelRow
 ld de,wZhMovePixels+394
 call .copyPixelRow
 ld de,wZhMovePixels+396
 call .copyPixelRow
 ld de,wZhMovePixels+398
 call .copyPixelRow
 ld de,wZhMovePixels+576
 call .copyPixelRow
 ld de,wZhMovePixels+578
 call .copyPixelRow
 ld de,wZhMovePixels+580
 call .copyPixelRow
 ld de,wZhMovePixels+406
 call .copyPixelRow
 ld de,wZhMovePixels+408
 call .copyPixelRow
 ld de,wZhMovePixels+410
 call .copyPixelRow
 ld de,wZhMovePixels+412
 call .copyPixelRow
 ld de,wZhMovePixels+414
 call .copyPixelRow
 ld de,wZhMovePixels+592
 call .copyPixelRow
 ld de,wZhMovePixels+594
 call .copyPixelRow
 ld de,wZhMovePixels+596
 call .copyPixelRow
 ld de,wZhMovePixels+422
 call .copyPixelRow
 ld de,wZhMovePixels+424
 call .copyPixelRow
 ld de,wZhMovePixels+426
 call .copyPixelRow
 ld de,wZhMovePixels+428
 call .copyPixelRow
 ld de,wZhMovePixels+430
 call .copyPixelRow
 ld de,wZhMovePixels+608
 call .copyPixelRow
 ld de,wZhMovePixels+610
 call .copyPixelRow
 ld de,wZhMovePixels+612
 call .copyPixelRow
 ld de,wZhMovePixels+438
 call .copyPixelRow
 ld de,wZhMovePixels+440
 call .copyPixelRow
 ld de,wZhMovePixels+442
 call .copyPixelRow
 ld de,wZhMovePixels+444
 call .copyPixelRow
 ld de,wZhMovePixels+446
 call .copyPixelRow
 ld de,wZhMovePixels+624
 call .copyPixelRow
 ld de,wZhMovePixels+626
 call .copyPixelRow
 ld de,wZhMovePixels+628
 call .copyPixelRow
 ld de,wZhMovePixels+454
 call .copyPixelRow
 ld de,wZhMovePixels+456
 call .copyPixelRow
 ld de,wZhMovePixels+458
 call .copyPixelRow
 ld de,wZhMovePixels+460
 call .copyPixelRow
 ld de,wZhMovePixels+462
 call .copyPixelRow
 ld de,wZhMovePixels+640
 call .copyPixelRow
 ld de,wZhMovePixels+642
 call .copyPixelRow
 ld de,wZhMovePixels+644
 call .copyPixelRow
 ld de,wZhMovePixels+470
 call .copyPixelRow
 ld de,wZhMovePixels+472
 call .copyPixelRow
 ld de,wZhMovePixels+474
 call .copyPixelRow
 ld de,wZhMovePixels+476
 call .copyPixelRow
 ld de,wZhMovePixels+478
 call .copyPixelRow
 ld de,wZhMovePixels+656
 call .copyPixelRow
 ld de,wZhMovePixels+658
 call .copyPixelRow
 ld de,wZhMovePixels+660
 call .copyPixelRow
 ld de,wZhMovePixels+486
 call .copyPixelRow
 ld de,wZhMovePixels+488
 call .copyPixelRow
 ld de,wZhMovePixels+490
 call .copyPixelRow
 ld de,wZhMovePixels+492
 call .copyPixelRow
 ld de,wZhMovePixels+494
 call .copyPixelRow
 ld de,wZhMovePixels+672
 call .copyPixelRow
 ld de,wZhMovePixels+674
 call .copyPixelRow
 ld de,wZhMovePixels+676
 call .copyPixelRow
 ld de,wZhMovePixels+502
 call .copyPixelRow
 ld de,wZhMovePixels+504
 call .copyPixelRow
 ld de,wZhMovePixels+506
 call .copyPixelRow
 ld de,wZhMovePixels+508
 call .copyPixelRow
 ld de,wZhMovePixels+510
 call .copyPixelRow
 ld de,wZhMovePixels+688
 call .copyPixelRow
 ld de,wZhMovePixels+690
 call .copyPixelRow
 ld de,wZhMovePixels+692
 call .copyPixelRow
 ld de,wZhMovePixels+582
 call .copyPixelRow
 ld de,wZhMovePixels+584
 call .copyPixelRow
 ld de,wZhMovePixels+586
 call .copyPixelRow
 ld de,wZhMovePixels+588
 call .copyPixelRow
 ld de,wZhMovePixels+590
 call .copyPixelRow
 ld de,wZhMovePixels+768
 call .copyPixelRow
 ld de,wZhMovePixels+770
 call .copyPixelRow
 ld de,wZhMovePixels+772
 call .copyPixelRow
 ld de,wZhMovePixels+598
 call .copyPixelRow
 ld de,wZhMovePixels+600
 call .copyPixelRow
 ld de,wZhMovePixels+602
 call .copyPixelRow
 ld de,wZhMovePixels+604
 call .copyPixelRow
 ld de,wZhMovePixels+606
 call .copyPixelRow
 ld de,wZhMovePixels+784
 call .copyPixelRow
 ld de,wZhMovePixels+786
 call .copyPixelRow
 ld de,wZhMovePixels+788
 call .copyPixelRow
 ld de,wZhMovePixels+614
 call .copyPixelRow
 ld de,wZhMovePixels+616
 call .copyPixelRow
 ld de,wZhMovePixels+618
 call .copyPixelRow
 ld de,wZhMovePixels+620
 call .copyPixelRow
 ld de,wZhMovePixels+622
 call .copyPixelRow
 ld de,wZhMovePixels+800
 call .copyPixelRow
 ld de,wZhMovePixels+802
 call .copyPixelRow
 ld de,wZhMovePixels+804
 call .copyPixelRow
 ld de,wZhMovePixels+630
 call .copyPixelRow
 ld de,wZhMovePixels+632
 call .copyPixelRow
 ld de,wZhMovePixels+634
 call .copyPixelRow
 ld de,wZhMovePixels+636
 call .copyPixelRow
 ld de,wZhMovePixels+638
 call .copyPixelRow
 ld de,wZhMovePixels+816
 call .copyPixelRow
 ld de,wZhMovePixels+818
 call .copyPixelRow
 ld de,wZhMovePixels+820
 call .copyPixelRow
 ld de,wZhMovePixels+646
 call .copyPixelRow
 ld de,wZhMovePixels+648
 call .copyPixelRow
 ld de,wZhMovePixels+650
 call .copyPixelRow
 ld de,wZhMovePixels+652
 call .copyPixelRow
 ld de,wZhMovePixels+654
 call .copyPixelRow
 ld de,wZhMovePixels+832
 call .copyPixelRow
 ld de,wZhMovePixels+834
 call .copyPixelRow
 ld de,wZhMovePixels+836
 call .copyPixelRow
 ld de,wZhMovePixels+662
 call .copyPixelRow
 ld de,wZhMovePixels+664
 call .copyPixelRow
 ld de,wZhMovePixels+666
 call .copyPixelRow
 ld de,wZhMovePixels+668
 call .copyPixelRow
 ld de,wZhMovePixels+670
 call .copyPixelRow
 ld de,wZhMovePixels+848
 call .copyPixelRow
 ld de,wZhMovePixels+850
 call .copyPixelRow
 ld de,wZhMovePixels+852
 call .copyPixelRow
 ld de,wZhMovePixels+678
 call .copyPixelRow
 ld de,wZhMovePixels+680
 call .copyPixelRow
 ld de,wZhMovePixels+682
 call .copyPixelRow
 ld de,wZhMovePixels+684
 call .copyPixelRow
 ld de,wZhMovePixels+686
 call .copyPixelRow
 ld de,wZhMovePixels+864
 call .copyPixelRow
 ld de,wZhMovePixels+866
 call .copyPixelRow
 ld de,wZhMovePixels+868
 call .copyPixelRow
 ld de,wZhMovePixels+694
 call .copyPixelRow
 ld de,wZhMovePixels+696
 call .copyPixelRow
 ld de,wZhMovePixels+698
 call .copyPixelRow
 ld de,wZhMovePixels+700
 call .copyPixelRow
 ld de,wZhMovePixels+702
 call .copyPixelRow
 ld de,wZhMovePixels+880
 call .copyPixelRow
 ld de,wZhMovePixels+882
 call .copyPixelRow
 ld de,wZhMovePixels+884
 call .copyPixelRow
 ld hl,.PP+0
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+648],a
 ld [wZhMovePixels+649],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+650],a
 ld [wZhMovePixels+651],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+652],a
 ld [wZhMovePixels+653],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+654],a
 ld [wZhMovePixels+655],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+832],a
 ld [wZhMovePixels+833],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+834],a
 ld [wZhMovePixels+835],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+836],a
 ld [wZhMovePixels+837],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+838],a
 ld [wZhMovePixels+839],a
.ppSkip1_0
 ld hl,.PP+8
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+664],a
 ld [wZhMovePixels+665],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+666],a
 ld [wZhMovePixels+667],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+668],a
 ld [wZhMovePixels+669],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+670],a
 ld [wZhMovePixels+671],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+848],a
 ld [wZhMovePixels+849],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+850],a
 ld [wZhMovePixels+851],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+852],a
 ld [wZhMovePixels+853],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+854],a
 ld [wZhMovePixels+855],a
.ppSkip1_1
 ld hl,.PP+16
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+680],a
 ld [wZhMovePixels+681],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+682],a
 ld [wZhMovePixels+683],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+684],a
 ld [wZhMovePixels+685],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+686],a
 ld [wZhMovePixels+687],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+864],a
 ld [wZhMovePixels+865],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+866],a
 ld [wZhMovePixels+867],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+868],a
 ld [wZhMovePixels+869],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+870],a
 ld [wZhMovePixels+871],a
.ppSkip1_2
 ld a,[wZhMovePPText+11]
 cp $7f
 jr z,.ppSkip1_3
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+696],a
 ld [wZhMovePixels+697],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+698],a
 ld [wZhMovePixels+699],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+700],a
 ld [wZhMovePixels+701],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+702],a
 ld [wZhMovePixels+703],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+880],a
 ld [wZhMovePixels+881],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+882],a
 ld [wZhMovePixels+883],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+884],a
 ld [wZhMovePixels+885],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+886],a
 ld [wZhMovePixels+887],a
.ppSkip1_3
 ld a,[wZhMovePPText+12]
 cp $7f
 jr z,.ppSkip1_4
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+712],a
 ld [wZhMovePixels+713],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+714],a
 ld [wZhMovePixels+715],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+716],a
 ld [wZhMovePixels+717],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+718],a
 ld [wZhMovePixels+719],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+896],a
 ld [wZhMovePixels+897],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+898],a
 ld [wZhMovePixels+899],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+900],a
 ld [wZhMovePixels+901],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+902],a
 ld [wZhMovePixels+903],a
.ppSkip1_4
 ld a,[wZhMovePPText+13]
 cp $7f
 jr z,.ppSkip1_5
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+728],a
 ld [wZhMovePixels+729],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+730],a
 ld [wZhMovePixels+731],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+732],a
 ld [wZhMovePixels+733],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+734],a
 ld [wZhMovePixels+735],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+912],a
 ld [wZhMovePixels+913],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+914],a
 ld [wZhMovePixels+915],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+916],a
 ld [wZhMovePixels+917],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+918],a
 ld [wZhMovePixels+919],a
.ppSkip1_5
 ld a,[wZhMovePPText+14]
 cp $7f
 jr z,.ppSkip1_6
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+744],a
 ld [wZhMovePixels+745],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+746],a
 ld [wZhMovePixels+747],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+748],a
 ld [wZhMovePixels+749],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+750],a
 ld [wZhMovePixels+751],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+928],a
 ld [wZhMovePixels+929],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+930],a
 ld [wZhMovePixels+931],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+932],a
 ld [wZhMovePixels+933],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+934],a
 ld [wZhMovePixels+935],a
.ppSkip1_6
 ld a,[wZhMovePPText+15]
 cp $7f
 jr z,.ppSkip1_7
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+760],a
 ld [wZhMovePixels+761],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+762],a
 ld [wZhMovePixels+763],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+764],a
 ld [wZhMovePixels+765],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+766],a
 ld [wZhMovePixels+767],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+944],a
 ld [wZhMovePixels+945],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+946],a
 ld [wZhMovePixels+947],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+948],a
 ld [wZhMovePixels+949],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+950],a
 ld [wZhMovePixels+951],a
.ppSkip1_7
.rowDone1
 ld a,[wZhMoveIds+2]
 and a
 jp z,.rowDone2
 call .lookup
 ld de,wZhMovePixels+780
 call .copyPixelRow
 ld de,wZhMovePixels+782
 call .copyPixelRow
 ld de,wZhMovePixels+960
 call .copyPixelRow
 ld de,wZhMovePixels+962
 call .copyPixelRow
 ld de,wZhMovePixels+964
 call .copyPixelRow
 ld de,wZhMovePixels+966
 call .copyPixelRow
 ld de,wZhMovePixels+968
 call .copyPixelRow
 ld de,wZhMovePixels+970
 call .copyPixelRow
 ld de,wZhMovePixels+796
 call .copyPixelRow
 ld de,wZhMovePixels+798
 call .copyPixelRow
 ld de,wZhMovePixels+976
 call .copyPixelRow
 ld de,wZhMovePixels+978
 call .copyPixelRow
 ld de,wZhMovePixels+980
 call .copyPixelRow
 ld de,wZhMovePixels+982
 call .copyPixelRow
 ld de,wZhMovePixels+984
 call .copyPixelRow
 ld de,wZhMovePixels+986
 call .copyPixelRow
 ld de,wZhMovePixels+812
 call .copyPixelRow
 ld de,wZhMovePixels+814
 call .copyPixelRow
 ld de,wZhMovePixels+992
 call .copyPixelRow
 ld de,wZhMovePixels+994
 call .copyPixelRow
 ld de,wZhMovePixels+996
 call .copyPixelRow
 ld de,wZhMovePixels+998
 call .copyPixelRow
 ld de,wZhMovePixels+1000
 call .copyPixelRow
 ld de,wZhMovePixels+1002
 call .copyPixelRow
 ld de,wZhMovePixels+828
 call .copyPixelRow
 ld de,wZhMovePixels+830
 call .copyPixelRow
 ld de,wZhMovePixels+1008
 call .copyPixelRow
 ld de,wZhMovePixels+1010
 call .copyPixelRow
 ld de,wZhMovePixels+1012
 call .copyPixelRow
 ld de,wZhMovePixels+1014
 call .copyPixelRow
 ld de,wZhMovePixels+1016
 call .copyPixelRow
 ld de,wZhMovePixels+1018
 call .copyPixelRow
 ld de,wZhMovePixels+844
 call .copyPixelRow
 ld de,wZhMovePixels+846
 call .copyPixelRow
 ld de,wZhMovePixels+1024
 call .copyPixelRow
 ld de,wZhMovePixels+1026
 call .copyPixelRow
 ld de,wZhMovePixels+1028
 call .copyPixelRow
 ld de,wZhMovePixels+1030
 call .copyPixelRow
 ld de,wZhMovePixels+1032
 call .copyPixelRow
 ld de,wZhMovePixels+1034
 call .copyPixelRow
 ld de,wZhMovePixels+860
 call .copyPixelRow
 ld de,wZhMovePixels+862
 call .copyPixelRow
 ld de,wZhMovePixels+1040
 call .copyPixelRow
 ld de,wZhMovePixels+1042
 call .copyPixelRow
 ld de,wZhMovePixels+1044
 call .copyPixelRow
 ld de,wZhMovePixels+1046
 call .copyPixelRow
 ld de,wZhMovePixels+1048
 call .copyPixelRow
 ld de,wZhMovePixels+1050
 call .copyPixelRow
 ld de,wZhMovePixels+876
 call .copyPixelRow
 ld de,wZhMovePixels+878
 call .copyPixelRow
 ld de,wZhMovePixels+1056
 call .copyPixelRow
 ld de,wZhMovePixels+1058
 call .copyPixelRow
 ld de,wZhMovePixels+1060
 call .copyPixelRow
 ld de,wZhMovePixels+1062
 call .copyPixelRow
 ld de,wZhMovePixels+1064
 call .copyPixelRow
 ld de,wZhMovePixels+1066
 call .copyPixelRow
 ld de,wZhMovePixels+892
 call .copyPixelRow
 ld de,wZhMovePixels+894
 call .copyPixelRow
 ld de,wZhMovePixels+1072
 call .copyPixelRow
 ld de,wZhMovePixels+1074
 call .copyPixelRow
 ld de,wZhMovePixels+1076
 call .copyPixelRow
 ld de,wZhMovePixels+1078
 call .copyPixelRow
 ld de,wZhMovePixels+1080
 call .copyPixelRow
 ld de,wZhMovePixels+1082
 call .copyPixelRow
 ld de,wZhMovePixels+972
 call .copyPixelRow
 ld de,wZhMovePixels+974
 call .copyPixelRow
 ld de,wZhMovePixels+1152
 call .copyPixelRow
 ld de,wZhMovePixels+1154
 call .copyPixelRow
 ld de,wZhMovePixels+1156
 call .copyPixelRow
 ld de,wZhMovePixels+1158
 call .copyPixelRow
 ld de,wZhMovePixels+1160
 call .copyPixelRow
 ld de,wZhMovePixels+1162
 call .copyPixelRow
 ld de,wZhMovePixels+988
 call .copyPixelRow
 ld de,wZhMovePixels+990
 call .copyPixelRow
 ld de,wZhMovePixels+1168
 call .copyPixelRow
 ld de,wZhMovePixels+1170
 call .copyPixelRow
 ld de,wZhMovePixels+1172
 call .copyPixelRow
 ld de,wZhMovePixels+1174
 call .copyPixelRow
 ld de,wZhMovePixels+1176
 call .copyPixelRow
 ld de,wZhMovePixels+1178
 call .copyPixelRow
 ld de,wZhMovePixels+1004
 call .copyPixelRow
 ld de,wZhMovePixels+1006
 call .copyPixelRow
 ld de,wZhMovePixels+1184
 call .copyPixelRow
 ld de,wZhMovePixels+1186
 call .copyPixelRow
 ld de,wZhMovePixels+1188
 call .copyPixelRow
 ld de,wZhMovePixels+1190
 call .copyPixelRow
 ld de,wZhMovePixels+1192
 call .copyPixelRow
 ld de,wZhMovePixels+1194
 call .copyPixelRow
 ld de,wZhMovePixels+1020
 call .copyPixelRow
 ld de,wZhMovePixels+1022
 call .copyPixelRow
 ld de,wZhMovePixels+1200
 call .copyPixelRow
 ld de,wZhMovePixels+1202
 call .copyPixelRow
 ld de,wZhMovePixels+1204
 call .copyPixelRow
 ld de,wZhMovePixels+1206
 call .copyPixelRow
 ld de,wZhMovePixels+1208
 call .copyPixelRow
 ld de,wZhMovePixels+1210
 call .copyPixelRow
 ld de,wZhMovePixels+1036
 call .copyPixelRow
 ld de,wZhMovePixels+1038
 call .copyPixelRow
 ld de,wZhMovePixels+1216
 call .copyPixelRow
 ld de,wZhMovePixels+1218
 call .copyPixelRow
 ld de,wZhMovePixels+1220
 call .copyPixelRow
 ld de,wZhMovePixels+1222
 call .copyPixelRow
 ld de,wZhMovePixels+1224
 call .copyPixelRow
 ld de,wZhMovePixels+1226
 call .copyPixelRow
 ld de,wZhMovePixels+1052
 call .copyPixelRow
 ld de,wZhMovePixels+1054
 call .copyPixelRow
 ld de,wZhMovePixels+1232
 call .copyPixelRow
 ld de,wZhMovePixels+1234
 call .copyPixelRow
 ld de,wZhMovePixels+1236
 call .copyPixelRow
 ld de,wZhMovePixels+1238
 call .copyPixelRow
 ld de,wZhMovePixels+1240
 call .copyPixelRow
 ld de,wZhMovePixels+1242
 call .copyPixelRow
 ld de,wZhMovePixels+1068
 call .copyPixelRow
 ld de,wZhMovePixels+1070
 call .copyPixelRow
 ld de,wZhMovePixels+1248
 call .copyPixelRow
 ld de,wZhMovePixels+1250
 call .copyPixelRow
 ld de,wZhMovePixels+1252
 call .copyPixelRow
 ld de,wZhMovePixels+1254
 call .copyPixelRow
 ld de,wZhMovePixels+1256
 call .copyPixelRow
 ld de,wZhMovePixels+1258
 call .copyPixelRow
 ld de,wZhMovePixels+1084
 call .copyPixelRow
 ld de,wZhMovePixels+1086
 call .copyPixelRow
 ld de,wZhMovePixels+1264
 call .copyPixelRow
 ld de,wZhMovePixels+1266
 call .copyPixelRow
 ld de,wZhMovePixels+1268
 call .copyPixelRow
 ld de,wZhMovePixels+1270
 call .copyPixelRow
 ld de,wZhMovePixels+1272
 call .copyPixelRow
 ld de,wZhMovePixels+1274
 call .copyPixelRow
 ld hl,.PP+0
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1038],a
 ld [wZhMovePixels+1039],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1216],a
 ld [wZhMovePixels+1217],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1218],a
 ld [wZhMovePixels+1219],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1220],a
 ld [wZhMovePixels+1221],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1222],a
 ld [wZhMovePixels+1223],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1224],a
 ld [wZhMovePixels+1225],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1226],a
 ld [wZhMovePixels+1227],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1228],a
 ld [wZhMovePixels+1229],a
.ppSkip2_0
 ld hl,.PP+8
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1054],a
 ld [wZhMovePixels+1055],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1232],a
 ld [wZhMovePixels+1233],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1234],a
 ld [wZhMovePixels+1235],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1236],a
 ld [wZhMovePixels+1237],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1238],a
 ld [wZhMovePixels+1239],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1240],a
 ld [wZhMovePixels+1241],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1242],a
 ld [wZhMovePixels+1243],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1244],a
 ld [wZhMovePixels+1245],a
.ppSkip2_1
 ld hl,.PP+16
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1070],a
 ld [wZhMovePixels+1071],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1248],a
 ld [wZhMovePixels+1249],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1250],a
 ld [wZhMovePixels+1251],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1252],a
 ld [wZhMovePixels+1253],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1254],a
 ld [wZhMovePixels+1255],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1256],a
 ld [wZhMovePixels+1257],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1258],a
 ld [wZhMovePixels+1259],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1260],a
 ld [wZhMovePixels+1261],a
.ppSkip2_2
 ld a,[wZhMovePPText+19]
 cp $7f
 jr z,.ppSkip2_3
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1086],a
 ld [wZhMovePixels+1087],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1264],a
 ld [wZhMovePixels+1265],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1266],a
 ld [wZhMovePixels+1267],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1268],a
 ld [wZhMovePixels+1269],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1270],a
 ld [wZhMovePixels+1271],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1272],a
 ld [wZhMovePixels+1273],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1274],a
 ld [wZhMovePixels+1275],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1276],a
 ld [wZhMovePixels+1277],a
.ppSkip2_3
 ld a,[wZhMovePPText+20]
 cp $7f
 jr z,.ppSkip2_4
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1102],a
 ld [wZhMovePixels+1103],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1280],a
 ld [wZhMovePixels+1281],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1282],a
 ld [wZhMovePixels+1283],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1284],a
 ld [wZhMovePixels+1285],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1286],a
 ld [wZhMovePixels+1287],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1288],a
 ld [wZhMovePixels+1289],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1290],a
 ld [wZhMovePixels+1291],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1292],a
 ld [wZhMovePixels+1293],a
.ppSkip2_4
 ld a,[wZhMovePPText+21]
 cp $7f
 jr z,.ppSkip2_5
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1118],a
 ld [wZhMovePixels+1119],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1296],a
 ld [wZhMovePixels+1297],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1298],a
 ld [wZhMovePixels+1299],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1300],a
 ld [wZhMovePixels+1301],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1302],a
 ld [wZhMovePixels+1303],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1304],a
 ld [wZhMovePixels+1305],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1306],a
 ld [wZhMovePixels+1307],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1308],a
 ld [wZhMovePixels+1309],a
.ppSkip2_5
 ld a,[wZhMovePPText+22]
 cp $7f
 jr z,.ppSkip2_6
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1134],a
 ld [wZhMovePixels+1135],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1312],a
 ld [wZhMovePixels+1313],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1314],a
 ld [wZhMovePixels+1315],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1316],a
 ld [wZhMovePixels+1317],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1318],a
 ld [wZhMovePixels+1319],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1320],a
 ld [wZhMovePixels+1321],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1322],a
 ld [wZhMovePixels+1323],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1324],a
 ld [wZhMovePixels+1325],a
.ppSkip2_6
 ld a,[wZhMovePPText+23]
 cp $7f
 jr z,.ppSkip2_7
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1150],a
 ld [wZhMovePixels+1151],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1328],a
 ld [wZhMovePixels+1329],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1330],a
 ld [wZhMovePixels+1331],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1332],a
 ld [wZhMovePixels+1333],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1334],a
 ld [wZhMovePixels+1335],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1336],a
 ld [wZhMovePixels+1337],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1338],a
 ld [wZhMovePixels+1339],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1340],a
 ld [wZhMovePixels+1341],a
.ppSkip2_7
.rowDone2
 ld a,[wZhMoveIds+3]
 and a
 jp z,.rowDone3
 call .lookup
 ld de,wZhMovePixels+1346
 call .copyPixelRow
 ld de,wZhMovePixels+1348
 call .copyPixelRow
 ld de,wZhMovePixels+1350
 call .copyPixelRow
 ld de,wZhMovePixels+1352
 call .copyPixelRow
 ld de,wZhMovePixels+1354
 call .copyPixelRow
 ld de,wZhMovePixels+1356
 call .copyPixelRow
 ld de,wZhMovePixels+1358
 call .copyPixelRow
 ld de,wZhMovePixels+1536
 call .copyPixelRow
 ld de,wZhMovePixels+1362
 call .copyPixelRow
 ld de,wZhMovePixels+1364
 call .copyPixelRow
 ld de,wZhMovePixels+1366
 call .copyPixelRow
 ld de,wZhMovePixels+1368
 call .copyPixelRow
 ld de,wZhMovePixels+1370
 call .copyPixelRow
 ld de,wZhMovePixels+1372
 call .copyPixelRow
 ld de,wZhMovePixels+1374
 call .copyPixelRow
 ld de,wZhMovePixels+1552
 call .copyPixelRow
 ld de,wZhMovePixels+1378
 call .copyPixelRow
 ld de,wZhMovePixels+1380
 call .copyPixelRow
 ld de,wZhMovePixels+1382
 call .copyPixelRow
 ld de,wZhMovePixels+1384
 call .copyPixelRow
 ld de,wZhMovePixels+1386
 call .copyPixelRow
 ld de,wZhMovePixels+1388
 call .copyPixelRow
 ld de,wZhMovePixels+1390
 call .copyPixelRow
 ld de,wZhMovePixels+1568
 call .copyPixelRow
 ld de,wZhMovePixels+1394
 call .copyPixelRow
 ld de,wZhMovePixels+1396
 call .copyPixelRow
 ld de,wZhMovePixels+1398
 call .copyPixelRow
 ld de,wZhMovePixels+1400
 call .copyPixelRow
 ld de,wZhMovePixels+1402
 call .copyPixelRow
 ld de,wZhMovePixels+1404
 call .copyPixelRow
 ld de,wZhMovePixels+1406
 call .copyPixelRow
 ld de,wZhMovePixels+1584
 call .copyPixelRow
 ld de,wZhMovePixels+1410
 call .copyPixelRow
 ld de,wZhMovePixels+1412
 call .copyPixelRow
 ld de,wZhMovePixels+1414
 call .copyPixelRow
 ld de,wZhMovePixels+1416
 call .copyPixelRow
 ld de,wZhMovePixels+1418
 call .copyPixelRow
 ld de,wZhMovePixels+1420
 call .copyPixelRow
 ld de,wZhMovePixels+1422
 call .copyPixelRow
 ld de,wZhMovePixels+1600
 call .copyPixelRow
 ld de,wZhMovePixels+1426
 call .copyPixelRow
 ld de,wZhMovePixels+1428
 call .copyPixelRow
 ld de,wZhMovePixels+1430
 call .copyPixelRow
 ld de,wZhMovePixels+1432
 call .copyPixelRow
 ld de,wZhMovePixels+1434
 call .copyPixelRow
 ld de,wZhMovePixels+1436
 call .copyPixelRow
 ld de,wZhMovePixels+1438
 call .copyPixelRow
 ld de,wZhMovePixels+1616
 call .copyPixelRow
 ld de,wZhMovePixels+1442
 call .copyPixelRow
 ld de,wZhMovePixels+1444
 call .copyPixelRow
 ld de,wZhMovePixels+1446
 call .copyPixelRow
 ld de,wZhMovePixels+1448
 call .copyPixelRow
 ld de,wZhMovePixels+1450
 call .copyPixelRow
 ld de,wZhMovePixels+1452
 call .copyPixelRow
 ld de,wZhMovePixels+1454
 call .copyPixelRow
 ld de,wZhMovePixels+1632
 call .copyPixelRow
 ld de,wZhMovePixels+1458
 call .copyPixelRow
 ld de,wZhMovePixels+1460
 call .copyPixelRow
 ld de,wZhMovePixels+1462
 call .copyPixelRow
 ld de,wZhMovePixels+1464
 call .copyPixelRow
 ld de,wZhMovePixels+1466
 call .copyPixelRow
 ld de,wZhMovePixels+1468
 call .copyPixelRow
 ld de,wZhMovePixels+1470
 call .copyPixelRow
 ld de,wZhMovePixels+1648
 call .copyPixelRow
 ld de,wZhMovePixels+1538
 call .copyPixelRow
 ld de,wZhMovePixels+1540
 call .copyPixelRow
 ld de,wZhMovePixels+1542
 call .copyPixelRow
 ld de,wZhMovePixels+1544
 call .copyPixelRow
 ld de,wZhMovePixels+1546
 call .copyPixelRow
 ld de,wZhMovePixels+1548
 call .copyPixelRow
 ld de,wZhMovePixels+1550
 call .copyPixelRow
 ld de,wZhMovePixels+1728
 call .copyPixelRow
 ld de,wZhMovePixels+1554
 call .copyPixelRow
 ld de,wZhMovePixels+1556
 call .copyPixelRow
 ld de,wZhMovePixels+1558
 call .copyPixelRow
 ld de,wZhMovePixels+1560
 call .copyPixelRow
 ld de,wZhMovePixels+1562
 call .copyPixelRow
 ld de,wZhMovePixels+1564
 call .copyPixelRow
 ld de,wZhMovePixels+1566
 call .copyPixelRow
 ld de,wZhMovePixels+1744
 call .copyPixelRow
 ld de,wZhMovePixels+1570
 call .copyPixelRow
 ld de,wZhMovePixels+1572
 call .copyPixelRow
 ld de,wZhMovePixels+1574
 call .copyPixelRow
 ld de,wZhMovePixels+1576
 call .copyPixelRow
 ld de,wZhMovePixels+1578
 call .copyPixelRow
 ld de,wZhMovePixels+1580
 call .copyPixelRow
 ld de,wZhMovePixels+1582
 call .copyPixelRow
 ld de,wZhMovePixels+1760
 call .copyPixelRow
 ld de,wZhMovePixels+1586
 call .copyPixelRow
 ld de,wZhMovePixels+1588
 call .copyPixelRow
 ld de,wZhMovePixels+1590
 call .copyPixelRow
 ld de,wZhMovePixels+1592
 call .copyPixelRow
 ld de,wZhMovePixels+1594
 call .copyPixelRow
 ld de,wZhMovePixels+1596
 call .copyPixelRow
 ld de,wZhMovePixels+1598
 call .copyPixelRow
 ld de,wZhMovePixels+1776
 call .copyPixelRow
 ld de,wZhMovePixels+1602
 call .copyPixelRow
 ld de,wZhMovePixels+1604
 call .copyPixelRow
 ld de,wZhMovePixels+1606
 call .copyPixelRow
 ld de,wZhMovePixels+1608
 call .copyPixelRow
 ld de,wZhMovePixels+1610
 call .copyPixelRow
 ld de,wZhMovePixels+1612
 call .copyPixelRow
 ld de,wZhMovePixels+1614
 call .copyPixelRow
 ld de,wZhMovePixels+1792
 call .copyPixelRow
 ld de,wZhMovePixels+1618
 call .copyPixelRow
 ld de,wZhMovePixels+1620
 call .copyPixelRow
 ld de,wZhMovePixels+1622
 call .copyPixelRow
 ld de,wZhMovePixels+1624
 call .copyPixelRow
 ld de,wZhMovePixels+1626
 call .copyPixelRow
 ld de,wZhMovePixels+1628
 call .copyPixelRow
 ld de,wZhMovePixels+1630
 call .copyPixelRow
 ld de,wZhMovePixels+1808
 call .copyPixelRow
 ld de,wZhMovePixels+1634
 call .copyPixelRow
 ld de,wZhMovePixels+1636
 call .copyPixelRow
 ld de,wZhMovePixels+1638
 call .copyPixelRow
 ld de,wZhMovePixels+1640
 call .copyPixelRow
 ld de,wZhMovePixels+1642
 call .copyPixelRow
 ld de,wZhMovePixels+1644
 call .copyPixelRow
 ld de,wZhMovePixels+1646
 call .copyPixelRow
 ld de,wZhMovePixels+1824
 call .copyPixelRow
 ld de,wZhMovePixels+1650
 call .copyPixelRow
 ld de,wZhMovePixels+1652
 call .copyPixelRow
 ld de,wZhMovePixels+1654
 call .copyPixelRow
 ld de,wZhMovePixels+1656
 call .copyPixelRow
 ld de,wZhMovePixels+1658
 call .copyPixelRow
 ld de,wZhMovePixels+1660
 call .copyPixelRow
 ld de,wZhMovePixels+1662
 call .copyPixelRow
 ld de,wZhMovePixels+1840
 call .copyPixelRow
 ld hl,.PP+0
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1604],a
 ld [wZhMovePixels+1605],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1606],a
 ld [wZhMovePixels+1607],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1608],a
 ld [wZhMovePixels+1609],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1610],a
 ld [wZhMovePixels+1611],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1612],a
 ld [wZhMovePixels+1613],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1614],a
 ld [wZhMovePixels+1615],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1792],a
 ld [wZhMovePixels+1793],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1794],a
 ld [wZhMovePixels+1795],a
.ppSkip3_0
 ld hl,.PP+8
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1620],a
 ld [wZhMovePixels+1621],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1622],a
 ld [wZhMovePixels+1623],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1624],a
 ld [wZhMovePixels+1625],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1626],a
 ld [wZhMovePixels+1627],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1628],a
 ld [wZhMovePixels+1629],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1630],a
 ld [wZhMovePixels+1631],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1808],a
 ld [wZhMovePixels+1809],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1810],a
 ld [wZhMovePixels+1811],a
.ppSkip3_1
 ld hl,.PP+16
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1636],a
 ld [wZhMovePixels+1637],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1638],a
 ld [wZhMovePixels+1639],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1640],a
 ld [wZhMovePixels+1641],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1642],a
 ld [wZhMovePixels+1643],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1644],a
 ld [wZhMovePixels+1645],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1646],a
 ld [wZhMovePixels+1647],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1824],a
 ld [wZhMovePixels+1825],a
 ld a,BANK(.PP)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1826],a
 ld [wZhMovePixels+1827],a
.ppSkip3_2
 ld a,[wZhMovePPText+27]
 cp $7f
 jr z,.ppSkip3_3
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1652],a
 ld [wZhMovePixels+1653],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1654],a
 ld [wZhMovePixels+1655],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1656],a
 ld [wZhMovePixels+1657],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1658],a
 ld [wZhMovePixels+1659],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1660],a
 ld [wZhMovePixels+1661],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1662],a
 ld [wZhMovePixels+1663],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1840],a
 ld [wZhMovePixels+1841],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1842],a
 ld [wZhMovePixels+1843],a
.ppSkip3_3
 ld a,[wZhMovePPText+28]
 cp $7f
 jr z,.ppSkip3_4
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1668],a
 ld [wZhMovePixels+1669],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1670],a
 ld [wZhMovePixels+1671],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1672],a
 ld [wZhMovePixels+1673],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1674],a
 ld [wZhMovePixels+1675],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1676],a
 ld [wZhMovePixels+1677],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1678],a
 ld [wZhMovePixels+1679],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1856],a
 ld [wZhMovePixels+1857],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1858],a
 ld [wZhMovePixels+1859],a
.ppSkip3_4
 ld a,[wZhMovePPText+29]
 cp $7f
 jr z,.ppSkip3_5
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1684],a
 ld [wZhMovePixels+1685],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1686],a
 ld [wZhMovePixels+1687],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1688],a
 ld [wZhMovePixels+1689],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1690],a
 ld [wZhMovePixels+1691],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1692],a
 ld [wZhMovePixels+1693],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1694],a
 ld [wZhMovePixels+1695],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1872],a
 ld [wZhMovePixels+1873],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1874],a
 ld [wZhMovePixels+1875],a
.ppSkip3_5
 ld a,[wZhMovePPText+30]
 cp $7f
 jr z,.ppSkip3_6
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1700],a
 ld [wZhMovePixels+1701],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1702],a
 ld [wZhMovePixels+1703],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1704],a
 ld [wZhMovePixels+1705],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1706],a
 ld [wZhMovePixels+1707],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1708],a
 ld [wZhMovePixels+1709],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1710],a
 ld [wZhMovePixels+1711],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1888],a
 ld [wZhMovePixels+1889],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1890],a
 ld [wZhMovePixels+1891],a
.ppSkip3_6
 ld a,[wZhMovePPText+31]
 cp $7f
 jr z,.ppSkip3_7
 sub $80
 ld l,a
 ld h,0
 add hl,hl
 add hl,hl
 add hl,hl
 ld de,FontNormal
 add hl,de
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1716],a
 ld [wZhMovePixels+1717],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1718],a
 ld [wZhMovePixels+1719],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1720],a
 ld [wZhMovePixels+1721],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1722],a
 ld [wZhMovePixels+1723],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1724],a
 ld [wZhMovePixels+1725],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1726],a
 ld [wZhMovePixels+1727],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1904],a
 ld [wZhMovePixels+1905],a
 ld a,BANK(FontNormal)
 call GetFarByte
 inc hl
 ld [wZhMovePixels+1906],a
 ld [wZhMovePixels+1907],a
.ppSkip3_7
.rowDone3
 xor a
 ldh [rVBK],a
 ld hl,$8800
 ld de,wZhMovePixels
 ld c,120
 ld b,BANK(@)
 call Get2bpp
 xor a
 ldh [rVBK],a
 pop af
 ldh [rWBK],a
 hlbgcoord 0,0,wSummaryScreenWindowBuffer
 ld [hl],128
 hlbgcoord 16,0,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 1,0,wSummaryScreenWindowBuffer
 ld [hl],129
 hlbgcoord 17,0,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 2,0,wSummaryScreenWindowBuffer
 ld [hl],130
 hlbgcoord 18,0,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 3,0,wSummaryScreenWindowBuffer
 ld [hl],131
 hlbgcoord 19,0,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 4,0,wSummaryScreenWindowBuffer
 ld [hl],132
 hlbgcoord 20,0,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 5,0,wSummaryScreenWindowBuffer
 ld [hl],133
 hlbgcoord 21,0,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 6,0,wSummaryScreenWindowBuffer
 ld [hl],134
 hlbgcoord 22,0,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 7,0,wSummaryScreenWindowBuffer
 ld [hl],135
 hlbgcoord 23,0,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 8,0,wSummaryScreenWindowBuffer
 ld [hl],136
 hlbgcoord 24,0,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 9,0,wSummaryScreenWindowBuffer
 ld [hl],137
 hlbgcoord 25,0,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 10,0,wSummaryScreenWindowBuffer
 ld [hl],138
 hlbgcoord 26,0,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 11,0,wSummaryScreenWindowBuffer
 ld [hl],139
 hlbgcoord 27,0,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 0,1,wSummaryScreenWindowBuffer
 ld [hl],140
 hlbgcoord 16,1,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 1,1,wSummaryScreenWindowBuffer
 ld [hl],141
 hlbgcoord 17,1,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 2,1,wSummaryScreenWindowBuffer
 ld [hl],142
 hlbgcoord 18,1,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 3,1,wSummaryScreenWindowBuffer
 ld [hl],143
 hlbgcoord 19,1,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 4,1,wSummaryScreenWindowBuffer
 ld [hl],144
 hlbgcoord 20,1,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 5,1,wSummaryScreenWindowBuffer
 ld [hl],145
 hlbgcoord 21,1,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 6,1,wSummaryScreenWindowBuffer
 ld [hl],146
 hlbgcoord 22,1,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 7,1,wSummaryScreenWindowBuffer
 ld [hl],147
 hlbgcoord 23,1,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 8,1,wSummaryScreenWindowBuffer
 ld [hl],148
 hlbgcoord 24,1,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 9,1,wSummaryScreenWindowBuffer
 ld [hl],149
 hlbgcoord 25,1,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 10,1,wSummaryScreenWindowBuffer
 ld [hl],150
 hlbgcoord 26,1,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 11,1,wSummaryScreenWindowBuffer
 ld [hl],151
 hlbgcoord 27,1,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 0,2,wSummaryScreenWindowBuffer
 ld [hl],152
 hlbgcoord 16,2,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 1,2,wSummaryScreenWindowBuffer
 ld [hl],153
 hlbgcoord 17,2,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 2,2,wSummaryScreenWindowBuffer
 ld [hl],154
 hlbgcoord 18,2,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 3,2,wSummaryScreenWindowBuffer
 ld [hl],155
 hlbgcoord 19,2,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 4,2,wSummaryScreenWindowBuffer
 ld [hl],156
 hlbgcoord 20,2,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 5,2,wSummaryScreenWindowBuffer
 ld [hl],157
 hlbgcoord 21,2,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 6,2,wSummaryScreenWindowBuffer
 ld [hl],158
 hlbgcoord 22,2,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 7,2,wSummaryScreenWindowBuffer
 ld [hl],159
 hlbgcoord 23,2,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 8,2,wSummaryScreenWindowBuffer
 ld [hl],160
 hlbgcoord 24,2,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 9,2,wSummaryScreenWindowBuffer
 ld [hl],161
 hlbgcoord 25,2,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 10,2,wSummaryScreenWindowBuffer
 ld [hl],162
 hlbgcoord 26,2,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 11,2,wSummaryScreenWindowBuffer
 ld [hl],163
 hlbgcoord 27,2,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 0,3,wSummaryScreenWindowBuffer
 ld [hl],164
 hlbgcoord 16,3,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 1,3,wSummaryScreenWindowBuffer
 ld [hl],165
 hlbgcoord 17,3,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 2,3,wSummaryScreenWindowBuffer
 ld [hl],166
 hlbgcoord 18,3,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 3,3,wSummaryScreenWindowBuffer
 ld [hl],167
 hlbgcoord 19,3,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 4,3,wSummaryScreenWindowBuffer
 ld [hl],168
 hlbgcoord 20,3,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 5,3,wSummaryScreenWindowBuffer
 ld [hl],169
 hlbgcoord 21,3,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 6,3,wSummaryScreenWindowBuffer
 ld [hl],170
 hlbgcoord 22,3,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 7,3,wSummaryScreenWindowBuffer
 ld [hl],171
 hlbgcoord 23,3,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 8,3,wSummaryScreenWindowBuffer
 ld [hl],172
 hlbgcoord 24,3,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 9,3,wSummaryScreenWindowBuffer
 ld [hl],173
 hlbgcoord 25,3,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 10,3,wSummaryScreenWindowBuffer
 ld [hl],174
 hlbgcoord 26,3,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 11,3,wSummaryScreenWindowBuffer
 ld [hl],175
 hlbgcoord 27,3,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 0,4,wSummaryScreenWindowBuffer
 ld [hl],176
 hlbgcoord 16,4,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 1,4,wSummaryScreenWindowBuffer
 ld [hl],177
 hlbgcoord 17,4,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 2,4,wSummaryScreenWindowBuffer
 ld [hl],178
 hlbgcoord 18,4,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 3,4,wSummaryScreenWindowBuffer
 ld [hl],179
 hlbgcoord 19,4,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 4,4,wSummaryScreenWindowBuffer
 ld [hl],180
 hlbgcoord 20,4,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 5,4,wSummaryScreenWindowBuffer
 ld [hl],181
 hlbgcoord 21,4,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 6,4,wSummaryScreenWindowBuffer
 ld [hl],182
 hlbgcoord 22,4,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 7,4,wSummaryScreenWindowBuffer
 ld [hl],183
 hlbgcoord 23,4,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 8,4,wSummaryScreenWindowBuffer
 ld [hl],184
 hlbgcoord 24,4,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 9,4,wSummaryScreenWindowBuffer
 ld [hl],185
 hlbgcoord 25,4,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 10,4,wSummaryScreenWindowBuffer
 ld [hl],186
 hlbgcoord 26,4,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 11,4,wSummaryScreenWindowBuffer
 ld [hl],187
 hlbgcoord 27,4,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 0,5,wSummaryScreenWindowBuffer
 ld [hl],188
 hlbgcoord 16,5,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 1,5,wSummaryScreenWindowBuffer
 ld [hl],189
 hlbgcoord 17,5,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 2,5,wSummaryScreenWindowBuffer
 ld [hl],190
 hlbgcoord 18,5,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 3,5,wSummaryScreenWindowBuffer
 ld [hl],191
 hlbgcoord 19,5,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 4,5,wSummaryScreenWindowBuffer
 ld [hl],192
 hlbgcoord 20,5,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 5,5,wSummaryScreenWindowBuffer
 ld [hl],193
 hlbgcoord 21,5,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 6,5,wSummaryScreenWindowBuffer
 ld [hl],194
 hlbgcoord 22,5,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 7,5,wSummaryScreenWindowBuffer
 ld [hl],195
 hlbgcoord 23,5,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 8,5,wSummaryScreenWindowBuffer
 ld [hl],196
 hlbgcoord 24,5,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 9,5,wSummaryScreenWindowBuffer
 ld [hl],197
 hlbgcoord 25,5,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 10,5,wSummaryScreenWindowBuffer
 ld [hl],198
 hlbgcoord 26,5,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 11,5,wSummaryScreenWindowBuffer
 ld [hl],199
 hlbgcoord 27,5,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 0,6,wSummaryScreenWindowBuffer
 ld [hl],200
 hlbgcoord 16,6,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 1,6,wSummaryScreenWindowBuffer
 ld [hl],201
 hlbgcoord 17,6,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 2,6,wSummaryScreenWindowBuffer
 ld [hl],202
 hlbgcoord 18,6,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 3,6,wSummaryScreenWindowBuffer
 ld [hl],203
 hlbgcoord 19,6,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 4,6,wSummaryScreenWindowBuffer
 ld [hl],204
 hlbgcoord 20,6,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 5,6,wSummaryScreenWindowBuffer
 ld [hl],205
 hlbgcoord 21,6,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 6,6,wSummaryScreenWindowBuffer
 ld [hl],206
 hlbgcoord 22,6,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 7,6,wSummaryScreenWindowBuffer
 ld [hl],207
 hlbgcoord 23,6,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 8,6,wSummaryScreenWindowBuffer
 ld [hl],208
 hlbgcoord 24,6,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 9,6,wSummaryScreenWindowBuffer
 ld [hl],209
 hlbgcoord 25,6,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 10,6,wSummaryScreenWindowBuffer
 ld [hl],210
 hlbgcoord 26,6,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 11,6,wSummaryScreenWindowBuffer
 ld [hl],211
 hlbgcoord 27,6,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 0,7,wSummaryScreenWindowBuffer
 ld [hl],212
 hlbgcoord 16,7,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 1,7,wSummaryScreenWindowBuffer
 ld [hl],213
 hlbgcoord 17,7,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 2,7,wSummaryScreenWindowBuffer
 ld [hl],214
 hlbgcoord 18,7,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 3,7,wSummaryScreenWindowBuffer
 ld [hl],215
 hlbgcoord 19,7,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 4,7,wSummaryScreenWindowBuffer
 ld [hl],216
 hlbgcoord 20,7,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 5,7,wSummaryScreenWindowBuffer
 ld [hl],217
 hlbgcoord 21,7,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 6,7,wSummaryScreenWindowBuffer
 ld [hl],218
 hlbgcoord 22,7,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 7,7,wSummaryScreenWindowBuffer
 ld [hl],219
 hlbgcoord 23,7,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 8,7,wSummaryScreenWindowBuffer
 ld [hl],220
 hlbgcoord 24,7,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 9,7,wSummaryScreenWindowBuffer
 ld [hl],221
 hlbgcoord 25,7,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 10,7,wSummaryScreenWindowBuffer
 ld [hl],222
 hlbgcoord 26,7,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 11,7,wSummaryScreenWindowBuffer
 ld [hl],223
 hlbgcoord 27,7,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 0,8,wSummaryScreenWindowBuffer
 ld [hl],224
 hlbgcoord 16,8,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 1,8,wSummaryScreenWindowBuffer
 ld [hl],225
 hlbgcoord 17,8,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 2,8,wSummaryScreenWindowBuffer
 ld [hl],226
 hlbgcoord 18,8,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 3,8,wSummaryScreenWindowBuffer
 ld [hl],227
 hlbgcoord 19,8,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 4,8,wSummaryScreenWindowBuffer
 ld [hl],228
 hlbgcoord 20,8,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 5,8,wSummaryScreenWindowBuffer
 ld [hl],229
 hlbgcoord 21,8,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 6,8,wSummaryScreenWindowBuffer
 ld [hl],230
 hlbgcoord 22,8,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 7,8,wSummaryScreenWindowBuffer
 ld [hl],231
 hlbgcoord 23,8,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 8,8,wSummaryScreenWindowBuffer
 ld [hl],232
 hlbgcoord 24,8,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 9,8,wSummaryScreenWindowBuffer
 ld [hl],233
 hlbgcoord 25,8,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 10,8,wSummaryScreenWindowBuffer
 ld [hl],234
 hlbgcoord 26,8,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 11,8,wSummaryScreenWindowBuffer
 ld [hl],235
 hlbgcoord 27,8,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 0,9,wSummaryScreenWindowBuffer
 ld [hl],236
 hlbgcoord 16,9,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 1,9,wSummaryScreenWindowBuffer
 ld [hl],237
 hlbgcoord 17,9,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 2,9,wSummaryScreenWindowBuffer
 ld [hl],238
 hlbgcoord 18,9,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 3,9,wSummaryScreenWindowBuffer
 ld [hl],239
 hlbgcoord 19,9,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 4,9,wSummaryScreenWindowBuffer
 ld [hl],240
 hlbgcoord 20,9,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 5,9,wSummaryScreenWindowBuffer
 ld [hl],241
 hlbgcoord 21,9,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 6,9,wSummaryScreenWindowBuffer
 ld [hl],242
 hlbgcoord 22,9,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 7,9,wSummaryScreenWindowBuffer
 ld [hl],243
 hlbgcoord 23,9,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 8,9,wSummaryScreenWindowBuffer
 ld [hl],244
 hlbgcoord 24,9,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 9,9,wSummaryScreenWindowBuffer
 ld [hl],245
 hlbgcoord 25,9,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 10,9,wSummaryScreenWindowBuffer
 ld [hl],246
 hlbgcoord 26,9,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 hlbgcoord 11,9,wSummaryScreenWindowBuffer
 ld [hl],247
 hlbgcoord 27,9,wSummaryScreenWindowBuffer
 ld [hl],SUMMARY_PAL_SIDE_WINDOW
 ld a,[wZhMoveIds+0]
 and a
 ld a,32
 jr nz,.sprite0_0
 xor a
.sprite0_0
 ld [wSummaryScreenOAMSprite04YCoord],a
 ld a,136
 ld [wSummaryScreenOAMSprite04XCoord],a
 ld a,[wZhMoveIds+0]
 and a
 ld a,32
 jr nz,.sprite0_1
 xor a
.sprite0_1
 ld [wSummaryScreenOAMSprite05YCoord],a
 ld a,144
 ld [wSummaryScreenOAMSprite05XCoord],a
 ld a,[wZhMoveIds+0]
 and a
 ld a,32
 jr nz,.sprite0_2
 xor a
.sprite0_2
 ld [wSummaryScreenOAMSprite06YCoord],a
 ld a,152
 ld [wSummaryScreenOAMSprite06XCoord],a
 ld a,[wZhMoveIds+0]
 and a
 ld a,32
 jr nz,.sprite0_3
 xor a
.sprite0_3
 ld [wSummaryScreenOAMSprite07YCoord],a
 ld a,160
 ld [wSummaryScreenOAMSprite07XCoord],a
 ld a,[wZhMoveIds+1]
 and a
 ld a,51
 jr nz,.sprite1_0
 xor a
.sprite1_0
 ld [wSummaryScreenOAMSprite08YCoord],a
 ld a,136
 ld [wSummaryScreenOAMSprite08XCoord],a
 ld a,[wZhMoveIds+1]
 and a
 ld a,51
 jr nz,.sprite1_1
 xor a
.sprite1_1
 ld [wSummaryScreenOAMSprite09YCoord],a
 ld a,144
 ld [wSummaryScreenOAMSprite09XCoord],a
 ld a,[wZhMoveIds+1]
 and a
 ld a,51
 jr nz,.sprite1_2
 xor a
.sprite1_2
 ld [wSummaryScreenOAMSprite10YCoord],a
 ld a,152
 ld [wSummaryScreenOAMSprite10XCoord],a
 ld a,[wZhMoveIds+1]
 and a
 ld a,51
 jr nz,.sprite1_3
 xor a
.sprite1_3
 ld [wSummaryScreenOAMSprite11YCoord],a
 ld a,160
 ld [wSummaryScreenOAMSprite11XCoord],a
 ld a,[wZhMoveIds+2]
 and a
 ld a,70
 jr nz,.sprite2_0
 xor a
.sprite2_0
 ld [wSummaryScreenOAMSprite12YCoord],a
 ld a,136
 ld [wSummaryScreenOAMSprite12XCoord],a
 ld a,[wZhMoveIds+2]
 and a
 ld a,70
 jr nz,.sprite2_1
 xor a
.sprite2_1
 ld [wSummaryScreenOAMSprite13YCoord],a
 ld a,144
 ld [wSummaryScreenOAMSprite13XCoord],a
 ld a,[wZhMoveIds+2]
 and a
 ld a,70
 jr nz,.sprite2_2
 xor a
.sprite2_2
 ld [wSummaryScreenOAMSprite14YCoord],a
 ld a,152
 ld [wSummaryScreenOAMSprite14XCoord],a
 ld a,[wZhMoveIds+2]
 and a
 ld a,70
 jr nz,.sprite2_3
 xor a
.sprite2_3
 ld [wSummaryScreenOAMSprite15YCoord],a
 ld a,160
 ld [wSummaryScreenOAMSprite15XCoord],a
 ld a,[wZhMoveIds+3]
 and a
 ld a,89
 jr nz,.sprite3_0
 xor a
.sprite3_0
 ld [wSummaryScreenOAMSprite16YCoord],a
 ld a,136
 ld [wSummaryScreenOAMSprite16XCoord],a
 ld a,[wZhMoveIds+3]
 and a
 ld a,89
 jr nz,.sprite3_1
 xor a
.sprite3_1
 ld [wSummaryScreenOAMSprite17YCoord],a
 ld a,144
 ld [wSummaryScreenOAMSprite17XCoord],a
 ld a,[wZhMoveIds+3]
 and a
 ld a,89
 jr nz,.sprite3_2
 xor a
.sprite3_2
 ld [wSummaryScreenOAMSprite18YCoord],a
 ld a,152
 ld [wSummaryScreenOAMSprite18XCoord],a
 ld a,[wZhMoveIds+3]
 and a
 ld a,89
 jr nz,.sprite3_3
 xor a
.sprite3_3
 ld [wSummaryScreenOAMSprite19YCoord],a
 ld a,160
 ld [wSummaryScreenOAMSprite19XCoord],a
 ret
.copyPixelRow
 ld a,b
 call GetFarByte
 inc hl
 ld [de],a
 inc de
 ld a,b
 call GetFarByte
 inc hl
 ld [de],a
 ret
.fallback
 ret
.lookup
 ld e,a
 ld d,0
 ld hl,ZhSummaryMoveNames
 add hl,de
 add hl,de
 add hl,de
 ld b,[hl]
 inc hl
 ld a,[hli]
 ld h,[hl]
 ld l,a
 or h
 ret nz
 scf
 ret

.PP:
 INCBIN "gfx/zh/summary_pp.1bpp"
